from dataclasses import dataclass, asdict


@dataclass
class BodyRecord:
    body_id: str
    victim_name: str
    location: str
    x: int
    y: int
    created_day: int
    discovered: bool = False
    buried: bool = False
    burying: bool = False
    burial_target_x: int = 0
    burial_target_y: int = 0
    is_werewolf_corpse: bool = False

    def to_status(self) -> dict:
        """
        Returns the dictionary representation of the BodyRecord using asdict,
        plus a sprite_key generated by replacing spaces in victim_name with underscores,
        and alive=False.
        """
        status = asdict(self)
        status['sprite_key'] = self.victim_name.replace(' ', '_')
        status['alive'] = False
        return status

@dataclass
class ClueRecord:
    clue_id: str
    clue_type: str
    summary: str
    source: str
    related_person: str
    location: str
    created_day: int
    delivered_to_crow: bool = False

def undelivered_clues_for(clues: list[ClueRecord], source: str) -> list[ClueRecord]:
    """
    Returns clues for the specified source where delivered_to_crow is False.
    """
    return [clue for clue in clues if clue.source == source and not clue.delivered_to_crow]
